modLoader="javafml"
loaderVersion="[4,)"
license="MPL-2.0"

[[mods]]
modId="notepad"
version="1.0.0"
displayName="Notely"
description="A client-side notepad mod with Markdown rendering and pinnable sticky notes. Write notes, create todos, and pin them to your HUD without leaving the game."
authors="Deokma"
logoFile="icon.png"

[[dependencies.notepad]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.notepad]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
